[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "arxiv_tracker"
version = "0.1.0"
description = "A tool for tracking new papers on arXiv"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "feedparser",
    "pandas",
]