name: Upload Python Package

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read


env:
    VERSION: ${{ github.run_number }}
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '<<'
        tokenSuffix: '>>'
        files: '["VERSION"]'

    - name: Bash - Show VERSION
      run: cat VERSION

    - name: Install package (modern, no .egg)
      run: pip install -e .
    - name: Test package
      run: python -m unittest discover
    - name: Build package
      run: python -m build
    - name: Publish package
      run: python -m twine upload dist/* -u${{ vars.PYPI_USERNAME }} -p${{ secrets.PYPI_PASSWORD }}
